{
 "title": "CPU Memoria y Pods Activosjga",
 "description": "Dashboard simple con CPU memoria en namespace jga",
 "tags": [
  "cpu",
  "memoria",
  "k8s",
  "jga"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU Total Usada (%) - Namespace jga",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"jga\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "Memoria Total Usada (bytes) - Namespace jga",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"jga\"})"
    }
   ]
  },
  {
   "title": "Cantidad de Pods Activos (Running) - Namespace jga",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace=\"jga\", phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Lista de Pods Activos (Running) - Namespace jga",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by (pod) (kube_pod_status_phase{namespace=\"jga\", phase=\"Running\"})"
    }
   ]
  }
 ]
}