#backend_service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: {{ .Values.service_backend.port }}
      targetPort: 8080
  type: {{ .Values.service_backend.type }}