apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.django.serviceName }}
spec:
  type: ClusterIP
  selector:
    app: django
  ports:
    - port: {{ .Values.django.containerPort }}
      targetPort: {{ .Values.django.containerPort }}
