#frontend_deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      initContainers:
        - name: wait-for-backend
          image: busybox
          command: [
            "sh",
            "-c",
            "until nc -z backend 8080; do echo esperando backend; sleep 5; done"
          ]
      containers:
        - name: frontend
          image: "{{ .Values.imagen_frontend.repository }}:{{ .Values.imagen_frontend.tag }}"
          imagePullPolicy: {{ .Values.imagen_frontend.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.2"
            limits:
              memory: "512Mi"
              cpu: "0.5"
